### ISSUE TITLE
The last default org overrides all open windows' setup

### ISSUE THREAD

**Issue by nerealegui** [victorgz/vscode-salesforce-colorg#1]
When opening 2 windows in VSCode with different projects, we can set as default org a different org in each window. 

The extension colours the bar of VSCode with the settings of the last org set by default, for all the windows opened at that moment. 

Could we get the settings by workspace instead of by user to avoid settings between windows to be overridden?

**Comment by victorgz** [comment]
New feature added on: [5fd341b2fe181d797098bbc5753419dc0dea1e6d](https://github.com/victorgz/vscode-salesforce-colorg/commit/5fd341b2fe181d797098bbc5753419dc0dea1e6d)
